"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import * as React from "react";
import {Providers} from "./providers";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <title>Lottery App</title>
      <body className={`${inter.className}`}>
        <Providers >
           {children}
       </Providers>  
        </body>
    </html>
  );
}
